#!/bin/bash

sudo socat -d -d pty,link=/dev/picoM,user="$USER",rawer,echo=0 pty,link=/dev/picoS,user="$USER",rawer,echo=0 &


sudo socat -d -d pty,link=/dev/picoMaestroM,user="$USER",rawer,echo=0 pty,link=/dev/picoMaestroS,user="$USER",rawer,echo=0 

